# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.6'
    - run: flutter pub get
    - run: flutter build apk
    - name: upload artifects
      uses: actions/upload-artifact@master
      with:
        name: android-app
        artifacts: "build/app/outputs/flutter-apkk/*.apk"
        token: ${{ secrets.TOKEN }}
         
